kamiwaza_version: 0.5.0
codename: noble
build_number: 439
arch: amd64  # Use 'auto' to detect, or specify 'amd64' or 'arm64' 
r2_endpoint_url: https://a8269aa1c3e707a1ce89dd67bdef4a0f.r2.cloudflarestorage.com
deb_file_url: https://packages.kamiwaza.ai/pool/main/k/kamiwaza/kamiwaza_v0.5.0_noble_amd64-rc1.deb
